services:
  - type: web
    name: cytotree-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: RENDER_EXTERNAL_HOSTNAME
        scope: blueprint

  - type: static_site
    name: cytotree-frontend
    buildCommand: cd frontend && npm install && VITE_API_URL=https://cytotree-backend.onrender.com npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://cytotree-backend.onrender.com
