services:
  - type: web
    name: cytotree-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend

  - type: static_site
    name: cytotree-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://cytotree-backend.onrender.com
